# -*- coding: utf-8 -*-
"""add_noise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VY7JcX5obuuMc0seEjPAV_MGVP-nm61N
"""

from pathlib import Path
from pydub import AudioSegment


BASE_DIR = Path(__file__).resolve().parent.parent
TTS_DIR = BASE_DIR / "tts" / "generated"
OUTPUT_DIR = Path(__file__).resolve().parent / "output"

OUTPUT_DIR.mkdir(exist_ok=True)


def add_noise(input_file, noise_file, output_file, noise_gain=-15):
    voice = AudioSegment.from_file(input_file)
    noise = AudioSegment.from_file(noise_file)

    # 음성 길이에 맞게 noise 반복
    while len(noise) < len(voice):
        noise += noise

    noise = noise[:len(voice)]

    # 노이즈 볼륨 감소
    noise = noise + noise_gain

    mixed = voice.overlay(noise)

    mixed.export(output_file, format="wav")

    print(f"[완료] {output_file}")


if __name__ == "__main__":

    voice_file = TTS_DIR / "announcement.mp3"

    # 실제 녹음한 생활소음 파일
    noise_file = BASE_DIR / "recording" / "samples" / "daily_noise.wav"

    output_file = OUTPUT_DIR / "announcement_with_noise.wav"

    add_noise(
        voice_file,
        noise_file,
        output_file
    )