# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SRI4yDK6oD9sbdPZDcW_fgdenLd5HEDK
"""

import os


# =====================================================
# Audio Classifier
# =====================================================

EMERGENCY_KEYWORDS = [
    "화재",
    "불이야",
    "응급",
    "긴급",
    "구급",
    "대피",
    "119",
    "사고"
]


def classify_text(text):

    text = text.strip()

    for keyword in EMERGENCY_KEYWORDS:

        if keyword in text:

            return "EMERGENCY"

    return "GENERAL"


# =====================================================
# Audio 파일 분류
# =====================================================

def classify_audio_file(
    file_path,
    recognized_text
):

    result = classify_text(
        recognized_text
    )

    print(
        f"Audio: {os.path.basename(file_path)}"
    )

    print(
        f"Text: {recognized_text}"
    )

    print(
        f"Classification: {result}"
    )

    return result


# =====================================================
# Test
# =====================================================

if __name__ == "__main__":

    tests = [  // 테스트용 코드
        "아파트 안내방송입니다",
        "화재가 발생했습니다",
        "긴급 대피하십시오"
    ]

    for text in tests:

        print(
            text,
            "→",
            classify_text(text)
        )