# -*- coding: utf-8 -*-
"""change_speed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AF1Kpgs1cgnmF-m92N8eOZcxc5HDvT2b
"""

from pathlib import Path
from pydub import AudioSegment


BASE_DIR = Path(__file__).resolve().parent.parent
INPUT_DIR = BASE_DIR / "tts" / "generated"
OUTPUT_DIR = Path(__file__).resolve().parent / "output"

OUTPUT_DIR.mkdir(exist_ok=True)


def change_speed(audio, speed=1.0):
    new_frame_rate = int(audio.frame_rate * speed)

    return audio._spawn(
        audio.raw_data,
        overrides={
            "frame_rate": new_frame_rate
        }
    ).set_frame_rate(audio.frame_rate)


if __name__ == "__main__":

    input_file = INPUT_DIR / "announcement.mp3"
    output_file = OUTPUT_DIR / "announcement_fast.wav"

    audio = AudioSegment.from_file(input_file)

    result = change_speed(
        audio,
        speed=1.2
    )

    result.export(
        output_file,
        format="wav"
    )

    print(f"[완료] {output_file}")