# -*- coding: utf-8 -*-
"""generate_tts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xB8GuI2zC7VliHGWocHaz3zlvuJHAOBX
"""

from pathlib import Path
from gtts import gTTS


BASE_DIR = Path(__file__).resolve().parent
TEXT_DIR = BASE_DIR / "text"
OUTPUT_DIR = BASE_DIR / "generated"

OUTPUT_DIR.mkdir(exist_ok=True)


FILES = {
    "dingdong": "dingdong.txt",
    "announcement": "announcement.txt",
    "emergency": "emergency.txt",
}


def generate_tts(name, filename):
    text_path = TEXT_DIR / filename
    output_path = OUTPUT_DIR / f"{name}.mp3"

    if not text_path.exists():
        print(f"[ERROR] 대본 파일이 없습니다: {text_path}")
        return

    text = text_path.read_text(encoding="utf-8").strip()

    if not text:
        print(f"[ERROR] 대본이 비어 있습니다: {text_path}")
        return

    print(f"[TTS] {name}.mp3 생성 중...")

    tts = gTTS(
        text=text,
        lang="ko",
        slow=False
    )

    tts.save(output_path)

    print(f"[완료] {output_path}")


def main():
    for name, filename in FILES.items():
        generate_tts(name, filename)

    print("\n모든 TTS 파일 생성 완료")


if __name__ == "__main__":
    main()