# -*- coding: utf-8 -*-
"""mix_audio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f1wZyEKJ02Job6Z06pDaOfPsUo5as-kN
"""

from pathlib import Path
from pydub import AudioSegment


BASE_DIR = Path(__file__).resolve().parent.parent
TTS_DIR = BASE_DIR / "tts" / "generated"
OUTPUT_DIR = Path(__file__).resolve().parent / "output"

OUTPUT_DIR.mkdir(exist_ok=True)


def mix_audio(files, output_file):

    result = AudioSegment.empty()

    for file in files:
        audio = AudioSegment.from_file(file)

        # 음성 사이에 1초 간격
        result += audio
        result += AudioSegment.silent(duration=1000)

    result.export(
        output_file,
        format="wav"
    )

    print(f"[완료] {output_file}")


if __name__ == "__main__":

    files = [
        TTS_DIR / "dingdong.mp3",
        TTS_DIR / "announcement.mp3"
    ]

    output_file = OUTPUT_DIR / "dingdong_then_announcement.wav"

    mix_audio(
        files,
        output_file
    )