# -*- coding: utf-8 -*-
"""csi_parser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wTcmCdvI7U9tM30UPrldMvdxhYQ8P9Bz
"""

import csv
import numpy as np
from pathlib import Path


INPUT_FILE = Path("data/csi/raw/csi_data.csv")
OUTPUT_FILE = Path("data/csi/processed/csi_amplitude.csv")


def load_csi_csv(file_path):
    """
    CSI CSV 파일을 읽어서
    timestamp와 CSI 데이터를 반환한다.
    """

    timestamps = []
    csi_data = []

    with open(file_path, "r", newline="", encoding="utf-8") as file:

        reader = csv.DictReader(file)

        for row in reader:

            timestamps.append(float(row["timestamp"]))

            values = []

            for key, value in row.items():

                if key == "timestamp":
                    continue

                try:
                    values.append(float(value))
                except (ValueError, TypeError):
                    values.append(0.0)

            csi_data.append(values)

    return np.array(timestamps), np.array(csi_data)


def calculate_amplitude(csi_data):
    """
    CSI 값에서 amplitude를 계산한다.

    이미 amplitude 값이 들어오는 경우에는
    그대로 반환한다.
    """

    return np.abs(csi_data)


def save_amplitude_csv(timestamps, amplitude, output_file):

    output_file.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    with open(
        output_file,
        "w",
        newline="",
        encoding="utf-8"
    ) as file:

        writer = csv.writer(file)

        header = ["timestamp"]

        for i in range(amplitude.shape[1]):
            header.append(f"sc{i}")

        writer.writerow(header)

        for timestamp, row in zip(timestamps, amplitude):

            writer.writerow(
                [timestamp] + row.tolist()
            )


def main():

    print("================================")
    print(" ZZIP CSI Parser")
    print("================================")

    if not INPUT_FILE.exists():

        print(f"[ERROR] File not found:")
        print(INPUT_FILE)

        return

    timestamps, csi_data = load_csi_csv(
        INPUT_FILE
    )

    print(f"Samples : {len(csi_data)}")
    print(f"Subcarriers : {csi_data.shape[1]}")

    amplitude = calculate_amplitude(
        csi_data
    )

    save_amplitude_csv(
        timestamps,
        amplitude,
        OUTPUT_FILE
    )

    print()
    print("Amplitude CSV created:")
    print(OUTPUT_FILE)


if __name__ == "__main__":
    main()