# -*- coding: utf-8 -*-
"""csi_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PoXpO5z5YeZllCCGTbm4H2mv095_tuVV
"""

import numpy as np
import pandas as pd
from pathlib import Path


INPUT_FILE = Path(
    "data/csi/processed/csi_amplitude.csv"
)

OUTPUT_FILE = Path(
    "data/csi/processed/csi_preprocessed.csv"
)


def moving_average(data, window=5):

    result = np.zeros_like(data)

    for i in range(data.shape[1]):

        series = pd.Series(data[:, i])

        result[:, i] = (
            series
            .rolling(
                window=window,
                center=True,
                min_periods=1
            )
            .mean()
            .values
        )

    return result


def normalize(data):

    mean = np.mean(data, axis=0)

    std = np.std(data, axis=0)

    std[std == 0] = 1

    return (data - mean) / std


def main():

    print("================================")
    print(" ZZIP CSI Preprocessing")
    print("================================")

    if not INPUT_FILE.exists():

        print("[ERROR] CSI file not found")

        return

    df = pd.read_csv(INPUT_FILE)

    timestamps = df["timestamp"].values

    csi = df.drop(
        columns=["timestamp"]
    ).values

    print(f"Samples : {len(csi)}")
    print(f"Subcarriers : {csi.shape[1]}")

    # --------------------------------
    # 1. Moving Average Filtering
    # --------------------------------

    filtered = moving_average(
        csi,
        window=5
    )

    # --------------------------------
    # 2. Normalization
    # --------------------------------

    normalized = normalize(
        filtered
    )

    result = pd.DataFrame(
        normalized,
        columns=[
            f"sc{i}"
            for i in range(
                normalized.shape[1]
            )
        ]
    )

    result.insert(
        0,
        "timestamp",
        timestamps
    )

    OUTPUT_FILE.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    result.to_csv(
        OUTPUT_FILE,
        index=False
    )

    print()
    print("Preprocessing completed.")
    print(f"Output : {OUTPUT_FILE}")


if __name__ == "__main__":
    main()