# -*- coding: utf-8 -*-
"""sleep_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xqZGcngx0rkWtzW56rsqHyNR0fWky3xI
"""

import pandas as pd
import numpy as np
from pathlib import Path


INPUT_FILE = Path(
    "data/csi/processed/csi_preprocessed.csv"
)


def calculate_motion(csi):

    # 시간에 따른 CSI 변화량
    diff = np.diff(
        csi,
        axis=0
    )

    # 전체 변화량
    motion = np.mean(
        np.abs(diff),
        axis=1
    )

    return motion


def classify_sleep(motion):

    threshold = 0.35

    average_motion = np.mean(
        motion
    )

    if average_motion < threshold:

        return "SLEEP"

    return "AWAKE"


def main():

    print("================================")
    print(" ZZIP Sleep Classifier")
    print("================================")

    if not INPUT_FILE.exists():

        print("[ERROR] Preprocessed CSI file not found")

        return

    df = pd.read_csv(
        INPUT_FILE
    )

    csi = df.drop(
        columns=["timestamp"]
    ).values

    motion = calculate_motion(
        csi
    )

    state = classify_sleep(
        motion
    )

    print()
    print("Average Motion :", np.mean(motion))
    print("Sleep State    :", state)


if __name__ == "__main__":
    main()