# -*- coding: utf-8 -*-
"""zzip_bridge.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rwm9Itr1HXSdFmWpNxJV-yZKNJO1Ssqx
"""

import serial
import time


# =====================================================
# 설정
# =====================================================

ARDUINO_PORT = "COM3"
BAUD_RATE = 9600


# =====================================================
# Arduino 연결
# =====================================================

def connect_arduino():

    arduino = serial.Serial(
        ARDUINO_PORT,
        BAUD_RATE,
        timeout=1
    )

    time.sleep(2)

    print(
        "Arduino connected:",
        ARDUINO_PORT
    )

    return arduino


# =====================================================
# 상태 전송
# =====================================================

def send_state(
    arduino,
    state
):

    valid_states = [
        "READY",
        "ZZIP",
        "EMERGENCY"
    ]

    state = state.upper()

    if state not in valid_states:

        print(
            "Invalid state:",
            state
        )

        return

    command = state + "\n"

    arduino.write(
        command.encode()
    )

    print(
        "[Bridge]",
        state
    )


# =====================================================
# Test
# =====================================================

if __name__ == "__main__":

    arduino = connect_arduino()

    try:

        send_state(
            arduino,
            "READY"
        )

        time.sleep(2)

        send_state(
            arduino,
            "ZZIP"
        )

        time.sleep(2)

        send_state(
            arduino,
            "EMERGENCY"
        )

    finally:

        arduino.close()

        print(
            "Arduino disconnected."
        )