# -*- coding: utf-8 -*-
"""zzip_logic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h1AKo8M8pwF_qCSnxl_404yAWeE4L69f
"""

# =====================================================
# ZZIP Logic
# =====================================================

class ZZIPLogic:

    def __init__(self):

        self.zzip_mode = False
        self.sleeping = False

    # -------------------------------------------------
    # ZZIP MODE
    # -------------------------------------------------

    def set_zzip_mode(
        self,
        enabled
    ):

        self.zzip_mode = enabled

        if enabled:

            print(
                "[ZZIP] ZZIP MODE ON"
            )

        else:

            print(
                "[ZZIP] ZZIP MODE OFF"
            )

    # -------------------------------------------------
    # Sleep state
    # -------------------------------------------------

    def set_sleep_state(
        self,
        sleeping
    ):

        self.sleeping = sleeping

    # -------------------------------------------------
    # 음성 상황 판단
    # -------------------------------------------------

    def process_audio(
        self,
        audio_type
    ):

        # ZZIP MODE가 아니면 그대로 전달
        if not self.zzip_mode:

            return "DELIVER_NOW"

        # 깨어있다면 그대로 전달
        if not self.sleeping:

            return "DELIVER_NOW"

        # 수면 중 긴급
        if audio_type == "EMERGENCY":

            return "EMERGENCY"

        # 수면 중 일반 안내
        return "STORE_FOR_LATER"


# =====================================================
# Test
# =====================================================

if __name__ == "__main__":

    logic = ZZIPLogic()

    logic.set_zzip_mode(True)
    logic.set_sleep_state(True)

    print(
        logic.process_audio(
            "GENERAL"
        )
    )

    print(
        logic.process_audio(
            "EMERGENCY"
        )
    )